; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=linx64 -O2 \
; RUN:   --linx-simt-autovec=1 --linx-simt-autovec-mode=mseq \
; RUN:   %s -o - | FileCheck %s

define void @sum_liveout(ptr nocapture noundef readonly %a, ptr nocapture noundef writeonly %out) local_unnamed_addr {
entry:
  br label %loop

loop:                                             ; preds = %loop, %entry
  %i = phi i64 [ 0, %entry ], [ %i.next, %loop ]
  %acc = phi float [ 0.000000e+00, %entry ], [ %acc.next, %loop ]
  %ptr = getelementptr inbounds float, ptr %a, i64 %i
  %val = load float, ptr %ptr, align 4
  %acc.next = fadd float %acc, %val
  %i.next = add nuw nsw i64 %i, 1
  %done = icmp eq i64 %i.next, 64
  br i1 %done, label %exit, label %loop

exit:                                             ; preds = %loop
  store float %acc.next, ptr %out, align 4
  ret void
}

; CHECK-LABEL: sum_liveout:
; CHECK: BSTART.MSEQ
; CHECK: B.IOR
; CHECK: B.IOTI
; CHECK: B.IOTI
; CHECK: C.B.DIMI 32, ->lb0
; CHECK: C.B.DIMI 2, ->lb1
; CHECK: v.lw.brg
; CHECK: c.movr
; CHECK: v.rdfadd
; CHECK: v.sw.brg.local a{{[0-5]}}, [ts
; CHECK: v.lw.brg.local [ts
; CHECK: v.sw.brg
