//===- PTOISA.h - PTO ISA ELF identity constants --------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
// Generated by llvm/utils/pto/generate_pto_isa_identity.py; do not edit.

#ifndef LLVM_BINARYFORMAT_PTOISA_H
#define LLVM_BINARYFORMAT_PTOISA_H

#include "llvm/ADT/StringRef.h"

namespace llvm::PTOISA {

#define LLVM_PTO_ISA_RELEASE "0.58.5"
#define LLVM_PTO_ISA_ENCODING_ABI "pto-isa-0.58.5-mode-function-v1"
#define LLVM_PTO_ISA_ENCODING_PROJECTION_SHA256                                \
  "747c509525579dc84038738c9a3ba26ae6ed4ef29a1d302cefb2a7b07fc150a8"

inline constexpr StringLiteral Release = LLVM_PTO_ISA_RELEASE;
inline constexpr StringLiteral EncodingABI = LLVM_PTO_ISA_ENCODING_ABI;
inline constexpr StringLiteral EncodingProjectionSHA256 =
    LLVM_PTO_ISA_ENCODING_PROJECTION_SHA256;
inline constexpr StringLiteral Identity =
    "{\"encoding_abi\":\"" LLVM_PTO_ISA_ENCODING_ABI
    "\",\"encoding_projection_sha256\":"
    "\"" LLVM_PTO_ISA_ENCODING_PROJECTION_SHA256
    "\",\"release\":\"" LLVM_PTO_ISA_RELEASE "\"}";

#undef LLVM_PTO_ISA_ENCODING_PROJECTION_SHA256
#undef LLVM_PTO_ISA_ENCODING_ABI
#undef LLVM_PTO_ISA_RELEASE

} // namespace llvm::PTOISA

#endif // LLVM_BINARYFORMAT_PTOISA_H
