#!/usr/bin/env python3
"""Generate LLVM's canonical PTO ISA ELF identity header from PTO-SPEC."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys


SHA256 = re.compile(r"[0-9a-f]{64}")
VERSION = re.compile(r"(?:0|[1-9][0-9]*)(?:\.(?:0|[1-9][0-9]*)){1,3}")


def identity_from_manifest(path: Path) -> dict[str, str]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("PTO release manifest must be an object")
    identity = {
        "release": value.get("release"),
        "encoding_abi": value.get("encoding_abi"),
        "encoding_projection_sha256": value.get("encoding_projection_sha256"),
    }
    if not isinstance(identity["release"], str) or VERSION.fullmatch(identity["release"]) is None:
        raise ValueError("PTO release manifest has an invalid release")
    if (
        not isinstance(identity["encoding_abi"], str)
        or identity["encoding_abi"] != f"pto-isa-{identity['release']}-mode-function-v1"
    ):
        raise ValueError("PTO release manifest encoding ABI does not match its release")
    if (
        not isinstance(identity["encoding_projection_sha256"], str)
        or SHA256.fullmatch(identity["encoding_projection_sha256"]) is None
    ):
        raise ValueError("PTO release manifest has an invalid encoding projection digest")
    return identity  # type: ignore[return-value]


def render(identity: dict[str, str]) -> str:
    release = identity["release"]
    abi = identity["encoding_abi"]
    digest = identity["encoding_projection_sha256"]
    return f'''//===- PTOISA.h - PTO ISA ELF identity constants --------------*- C++ -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
// Generated by llvm/utils/pto/generate_pto_isa_identity.py; do not edit.

#ifndef LLVM_BINARYFORMAT_PTOISA_H
#define LLVM_BINARYFORMAT_PTOISA_H

#include "llvm/ADT/StringRef.h"

namespace llvm::PTOISA {{

#define LLVM_PTO_ISA_RELEASE "{release}"
#define LLVM_PTO_ISA_ENCODING_ABI "{abi}"
#define LLVM_PTO_ISA_ENCODING_PROJECTION_SHA256                                \\
  "{digest}"

inline constexpr StringLiteral Release = LLVM_PTO_ISA_RELEASE;
inline constexpr StringLiteral EncodingABI = LLVM_PTO_ISA_ENCODING_ABI;
inline constexpr StringLiteral EncodingProjectionSHA256 =
    LLVM_PTO_ISA_ENCODING_PROJECTION_SHA256;
inline constexpr StringLiteral Identity =
    "{{\\"encoding_abi\\":\\"" LLVM_PTO_ISA_ENCODING_ABI
    "\\",\\"encoding_projection_sha256\\":"
    "\\"" LLVM_PTO_ISA_ENCODING_PROJECTION_SHA256
    "\\",\\"release\\":\\"" LLVM_PTO_ISA_RELEASE "\\"}}";

#undef LLVM_PTO_ISA_ENCODING_PROJECTION_SHA256
#undef LLVM_PTO_ISA_ENCODING_ABI
#undef LLVM_PTO_ISA_RELEASE

}} // namespace llvm::PTOISA

#endif // LLVM_BINARYFORMAT_PTOISA_H
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    try:
        expected = render(identity_from_manifest(arguments.manifest))
        if arguments.check:
            actual = arguments.output.read_text(encoding="utf-8")
            if actual != expected:
                print(f"stale generated PTO ISA identity: {arguments.output}", file=sys.stderr)
                return 1
        else:
            arguments.output.parent.mkdir(parents=True, exist_ok=True)
            arguments.output.write_text(expected, encoding="utf-8")
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"cannot generate PTO ISA identity: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
